# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"\x87\x01\n\x0fProductResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x0e\n\x06precio\x18\x04 \x01(\x02\x12\x16\n\x0e\x66\x65\x63ha_creacion\x18\x05 \x01(\t\x12\x1b\n\x13\x66\x65\x63ha_actualizacion\x18\x06 \x01(\t\"K\n\x14\x43reateProductRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x02 \x01(\t\x12\x0e\n\x06precio\x18\x03 \x01(\x02\"\x1f\n\x11GetProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"W\n\x14UpdateProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x0e\n\x06precio\x18\x04 \x01(\x02\"\"\n\x14\x44\x65leteProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"(\n\x15\x44\x65leteProductResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x15\n\x13ListProductsRequest\"B\n\x14ListProductsResponse\x12*\n\x08products\x18\x01 \x03(\x0b\x32\x18.product.ProductResponse2\x85\x03\n\x0eProductService\x12H\n\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x18.product.ProductResponse\x12\x42\n\nGetProduct\x12\x1a.product.GetProductRequest\x1a\x18.product.ProductResponse\x12H\n\rUpdateProduct\x12\x1d.product.UpdateProductRequest\x1a\x18.product.ProductResponse\x12N\n\rDeleteProduct\x12\x1d.product.DeleteProductRequest\x1a\x1e.product.DeleteProductResponse\x12K\n\x0cListProducts\x12\x1c.product.ListProductsRequest\x1a\x1d.product.ListProductsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTRESPONSE']._serialized_start=27
  _globals['_PRODUCTRESPONSE']._serialized_end=162
  _globals['_CREATEPRODUCTREQUEST']._serialized_start=164
  _globals['_CREATEPRODUCTREQUEST']._serialized_end=239
  _globals['_GETPRODUCTREQUEST']._serialized_start=241
  _globals['_GETPRODUCTREQUEST']._serialized_end=272
  _globals['_UPDATEPRODUCTREQUEST']._serialized_start=274
  _globals['_UPDATEPRODUCTREQUEST']._serialized_end=361
  _globals['_DELETEPRODUCTREQUEST']._serialized_start=363
  _globals['_DELETEPRODUCTREQUEST']._serialized_end=397
  _globals['_DELETEPRODUCTRESPONSE']._serialized_start=399
  _globals['_DELETEPRODUCTRESPONSE']._serialized_end=439
  _globals['_LISTPRODUCTSREQUEST']._serialized_start=441
  _globals['_LISTPRODUCTSREQUEST']._serialized_end=462
  _globals['_LISTPRODUCTSRESPONSE']._serialized_start=464
  _globals['_LISTPRODUCTSRESPONSE']._serialized_end=530
  _globals['_PRODUCTSERVICE']._serialized_start=533
  _globals['_PRODUCTSERVICE']._serialized_end=922
# @@protoc_insertion_point(module_scope)
